import io
from flask import Blueprint, request, jsonify, send_file

bp = Blueprint("export", __name__)

@bp.route("/export/pdf", methods=["POST"])
def export_pdf():
    data = request.get_json(silent=True) or {}
    bullets = data.get("bullets", [])
    keywords = data.get("keywords", [])
    flashcards = data.get("flashcards", [])
    quiz = data.get("quiz", [])
    title = data.get("title", "NoteBot Premium Intelligence Report")

    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib import colors
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, ListFlowable, ListItem
        from reportlab.lib.units import cm

        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=A4,
                                rightMargin=2*cm, leftMargin=2*cm,
                                topMargin=2*cm, bottomMargin=2*cm)
        styles = getSampleStyleSheet()

        title_style = ParagraphStyle("Title", parent=styles["Title"],
                                     fontSize=24, textColor=colors.HexColor("#7c3aed"), spaceAfter=12, fontName="Helvetica-Bold")
        sub_style = ParagraphStyle("Sub", parent=styles["Normal"],
                                   fontSize=11, textColor=colors.HexColor("#8884aa"), spaceAfter=20)
        h2_style = ParagraphStyle("H2", parent=styles["Heading2"],
                                  fontSize=16, textColor=colors.HexColor("#a78bfa"), spaceAfter=12, spaceBefore=20)
        h3_style = ParagraphStyle("H3", parent=styles["Heading3"],
                                  fontSize=12, textColor=colors.HexColor("#3a3650"), spaceAfter=6, fontName="Helvetica-Bold")
        body_style = ParagraphStyle("Body", parent=styles["Normal"],
                                    fontSize=11, leading=16, spaceAfter=8, textColor=colors.HexColor("#333333"))
        kw_style = ParagraphStyle("KW", parent=styles["Normal"],
                                  fontSize=10, textColor=colors.HexColor("#7c3aed"), spaceAfter=12)

        elements = [
            Paragraph(title, title_style),
            Paragraph("Generated by NoteBot Premium · The Immersive AI Study Workspace", sub_style),
            HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#7c3aed"), spaceAfter=24),
        ]

        if bullets:
            elements.append(Paragraph("Intelligent Summary", h2_style))
            bullet_items = []
            for b in bullets:
                text = b.get("text", b) if isinstance(b, dict) else str(b)
                bullet_items.append(ListItem(Paragraph(text, body_style), bulletColor=colors.HexColor("#7c3aed")))
            elements.append(ListFlowable(bullet_items, bulletType='bullet', leftIndent=15))

        if keywords:
            elements.append(Paragraph("Key Concepts", h2_style))
            elements.append(Paragraph(" · ".join(keywords), kw_style))

        if flashcards:
            elements.append(Paragraph("Flashcards", h2_style))
            for i, f in enumerate(flashcards, 1):
                elements.append(Paragraph(f"Q{i}: {f.get('question', '')}", h3_style))
                elements.append(Paragraph(f"A: {f.get('answer', '')}", body_style))
                elements.append(Spacer(1, 6))

        if quiz:
            elements.append(Paragraph("Assessment Quiz", h2_style))
            for i, q in enumerate(quiz, 1):
                elements.append(Paragraph(f"{i}. {q.get('question', '')}", h3_style))
                for opt in q.get("options", []):
                    prefix = "[ ✓ ]" if opt == q.get("correct") else "[   ]"
                    elements.append(Paragraph(f"{prefix} {opt}", body_style))
                elements.append(Spacer(1, 8))

        doc.build(elements)
        buf.seek(0)
        return send_file(buf, mimetype="application/pdf",
                         as_attachment=True, download_name="notebot_intelligence_report.pdf")
    except ImportError:
        return jsonify({"error": "reportlab not installed"}), 500
    except Exception as e:
        return jsonify({"error": str(e)}), 500
